using System;
using System.Collections.Generic;
using System.Text;

namespace People.Domain
{
    public class PeopleProvider
    {
        private Person[] GetAutoGeneratedPeople(int number)
        {
            List<Person> people = new List<Person>();

            for (int i = 0; i < number; i++)
            {
                string firstName = string.Format("Name{0}", i);
                string lastName = string.Format("Lastname{0}", i);
                string phone = GeneratePhoneNumber();

                Person singlePerson = new Person(firstName, lastName, phone);
                people.Add(singlePerson);
            }

            return people.ToArray();
        }

        private Random rnd = new Random();

        private string GeneratePhoneNumber()
        {
            int numLength = 10;
            StringBuilder number = new StringBuilder(numLength);
            
            for (int i = 0; i < numLength; i++)
                number.Append(rnd.Next(9));

            return number.ToString();
        }

        public Person[] GetPeople()
        {
            return GetAutoGeneratedPeople(20);
        }
    }
}
